[tool.poetry]
name = "update-deps"
version = "0.1.0"
description = ""
authors = ["Celine Lay <layceline@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^3.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
